# Generated by Django 3.1.7 on 2021-02-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20210226_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
