# Generated by Django 3.1.7 on 2021-03-01 11:53

from django.db import migrations, models
import django.db.models.deletion
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_remove_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=secrets.token_urlsafe, editable=False, verbose_name='Access Token')),
                ('created', models.DateTimeField(editable=False, verbose_name='Time the token has been generated')),
                ('valid_time', models.IntegerField(default=90, verbose_name='Minutes the token is valid for')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='control.course')),
            ],
        ),
    ]
