# Generated by Django 3.1.7 on 2021-03-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_auto_20210301_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='access_token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='control.accesstoken'),
        ),
    ]
