# Generated by Django 3.1.7 on 2021-03-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_auto_20210303_1016'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weekday',
            name='control_weekday_day_valid',
        ),
        migrations.AddConstraint(
            model_name='weekday',
            constraint=models.CheckConstraint(check=models.Q(day__in=['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']), name='control_weekday_day_valid'),
        ),
    ]
