# Generated by Django 3.1.7 on 2021-03-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_auto_20210303_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_ongoing',
            new_name='ongoing',
        ),
    ]
