# Generated by Django 3.1.7 on 2021-03-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_auto_20210303_1045'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weekday',
            name='control_weekday_day_valid',
        ),
        migrations.AlterField(
            model_name='weekday',
            name='day',
            field=models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1, max_length=3, verbose_name='course day'),
        ),
        migrations.AddConstraint(
            model_name='weekday',
            constraint=models.CheckConstraint(check=models.Q(day__in=[1, 2, 3, 4, 5, 6, 7]), name='control_weekday_day_valid'),
        ),
    ]
