# Generated by Django 3.1.7 on 2021-03-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_auto_20210303_1051'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weekday',
            name='control_weekday_day_valid',
        ),
        migrations.AlterField(
            model_name='weekday',
            name='day',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, max_length=3, verbose_name='course day'),
        ),
        migrations.AddConstraint(
            model_name='weekday',
            constraint=models.CheckConstraint(check=models.Q(day__in=[0, 1, 2, 3, 4, 5, 6]), name='control_weekday_day_valid'),
        ),
    ]
