# Generated by Django 3.1.7 on 2021-03-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_article_reporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='start_times',
        ),
        migrations.AddField(
            model_name='weekday',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_times', to='control.course'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
