# Generated by Django 3.1.7 on 2021-03-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_auto_20210305_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeRequests',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, max_length=20, null=True)),
                ('vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('ssid', models.CharField(blank=True, max_length=200, null=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('raw', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'probe_requests',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='control.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='additional_courses',
            field=models.ManyToManyField(related_name='additional_teachers', to='control.Course'),
        ),
        migrations.AlterField(
            model_name='weekday',
            name='day',
            field=models.IntegerField(choices=[(0, 'MON'), (1, 'TUE'), (2, 'WED'), (3, 'THU'), (4, 'FRI'), (5, 'SAT'), (6, 'SUN')], default=0, verbose_name='course day'),
        ),
    ]
