# Generated by Django 3.1.7 on 2021-03-13 15:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0019_auto_20210312_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end date of the course'),
        ),
        migrations.AddField(
            model_name='course',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date of the course'),
        ),
        migrations.AddField(
            model_name='course',
            name='token_valid_time',
            field=models.IntegerField(default=90, verbose_name='time until the registration token expires'),
        ),
        migrations.AddField(
            model_name='weekday',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weekday',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('attended', models.BooleanField(verbose_name='has attended course')),
                ('weekday', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.weekday')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
