# Generated by Django 3.1.7 on 2021-03-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_auto_20210313_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
