# Generated by Django 3.1.7 on 2021-03-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0022_auto_20210313_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstoken',
            name='modified',
        ),
    ]
