# Generated by Django 3.1.7 on 2021-05-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0026_auto_20210327_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probemon',
            fields=[
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='control.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
