# Generated by Django 3.1.7 on 2021-05-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0029_auto_20210515_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='wifi_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.wifiinfo'),
        ),
    ]
