# Generated by Django 3.1.7 on 2021-05-16 09:33

from django.db import migrations
import macaddress.fields


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0031_proberequest_mac_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifiinfo',
            name='mac',
            field=macaddress.fields.MACAddressField(integer=False, max_length=17, null=True, unique=True),
        ),
    ]
