# Generated by Django 3.1.7 on 2021-06-10 10:51

import django.core.serializers.json
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0032_auto_20210516_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiinfo',
            name='arrival_slot',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='wifiinfo',
            name='latest_recieved_probe_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wifiinfo',
            name='state',
            field=django_fsm.FSMField(choices=[('initial stage', 'Initial Stage'), ('arrive confirmation', 'Arrive Confirmation'), ('departure confirmation', 'Departure Confirmation')], default='initial stage', max_length=50, protected=True),
        ),
        migrations.AlterField(
            model_name='wifiinfo',
            name='mac_burst_interval',
            field=models.FloatField(default=3600),
        ),
    ]
