# Generated by Django 3.1.7 on 2021-06-13 20:23

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0033_auto_20210610_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestudentattendance',
            name='attendance_dates',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='arrival',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='departure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_dates', to='control.coursestudentattendance'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='has attended course'),
        ),
        migrations.AlterField(
            model_name='wifiinfo',
            name='state',
            field=django_fsm.FSMField(choices=[('initial stage', 'Initial Stage'), ('potential arrival', 'Potential Arrival'), ('arrive confirmation', 'Arrive Confirmation'), ('potential departure', 'Potential Departure'), ('departure confirmation', 'Departure Confirmation')], default='initial stage', max_length=50, protected=True),
        ),
    ]
