# Generated by Django 3.1.7 on 2021-07-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0034_auto_20210613_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wifiinfo',
            name='arrival_slot',
        ),
    ]
