# Generated by Django 3.1.7 on 2021-07-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0035_remove_wifiinfo_arrival_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='attended',
        ),
    ]
