# Generated by Django 3.1.7 on 2021-07-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0036_remove_attendancerecord_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='attended',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
