# Generated by Django 3.1.7 on 2021-07-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0037_attendancerecord_attended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wifiinfo',
            old_name='mac_burst_count',
            new_name='burst_count',
        ),
        migrations.RenameField(
            model_name='wifiinfo',
            old_name='mac_burst_interval',
            new_name='burst_interval',
        ),
        migrations.RenameField(
            model_name='wifiinfo',
            old_name='mac_burst_updated',
            new_name='burst_updated',
        ),
        migrations.AddField(
            model_name='wifiinfo',
            name='burst_variance',
            field=models.FloatField(db_column='mac_burst_variance', default=900),
        ),
        migrations.AlterField(
            model_name='wifiinfo',
            name='burst_count',
            field=models.PositiveIntegerField(db_column='mac_burst_count', default=0),
        ),
        migrations.AlterField(
            model_name='wifiinfo',
            name='burst_interval',
            field=models.FloatField(db_column='mac_burst_interval', default=3600),
        ),
        migrations.AlterField(
            model_name='wifiinfo',
            name='burst_updated',
            field=models.DateTimeField(blank=True, db_column='mac_burst_updated', null=True),
        ),
    ]
