# Generated by Django 3.1.7 on 2021-07-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0038_auto_20210704_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='attended',
            new_name='time_present',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='time_present',
            field=models.PositiveSmallIntegerField(db_column='attended', default=0),
        ),
    ]
