# Generated by Django 3.1.7 on 2021-07-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0039_auto_20210704_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='time_present',
            field=models.FloatField(db_column='attended', default=0.0),
        ),
    ]
